config/routes.rb
Rails.application.routes.draw do
 
  resources :images
  root 'welcome#index'

  resources :categories

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/account' => 'users#show'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id]
	  	@current_user ||= User.find(session[:user_id])
	else
		@current_user = nil
	end
  end

  helper_method :current_user

  def authorize
  	if current_user == nil
  		redirect_to 'login_path'
  	end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:photo, :name)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:svg, :category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	# login form
	def new
	end

	# log the person in
	def create
		user = User.find_by_email(params[:email])

		#if user is found and they typed in the right pw
		if user && user.authenticate(params[:password])

			# remember which user they are logged in as,
			# by storing in the session (cookies) 
			session[:user_id] = user.id
			redirect_to categories_path
		else
			redirect_to login_path
		end
	end

	# log the person out
	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new #renders new template
     @user = User.new
  end    

  def create
  	@user = User.new(user_params)
  	if @user.save # validations
  		session[:user_id] = @user.id
  		redirect_to root_path
  	else
  		redirect_to signup_path
  	end
  end

  def show
    @user = current_user
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@page_class = "welcome"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<% @categories.each do |category| %>
<table>
  <thead>
    <tr>
      <th><%= link_to category.name, category %></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><div class="category-placeholder"><%= link_to image_tag(category.photo), category%></div></td>
<!--         <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
  </tbody>
</table>
<% end %>
<br>

<!-- <%= link_to 'New Category', new_category_path %> -->

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @category.name %></h1>


<% @category.images.each do |image| %>
<table>
  	<tbody>
      <tr>
        <td><div class="category-placeholder"><%= link_to image.svg.html_safe, image %></div></td>
      </tr>
  	</tbody>
</table>

<% end %>

<div class="back"><%= link_to 'Back', categories_path %></div>

<!--
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :svg %><br>
    <%= f.text_area :svg %>
  </div>
    <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Svg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.svg.html_safe %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Start Colouring!</h2>

<div id="image">
  <%= @image.svg.html_safe %>
</div>


<div id="farbtastic">
	<div id="colorpicker"></div>
<!-- <form><input type="text" id="color" name="color" value="#800813" /></form> -->
	<div id='result'>
		<span id='picked'></span>
	</div>
</div>



<div class="back"> 
	<%= link_to 'Back', categories_path %> || 
	<div id="save"> <%= link_to 'Save', account_path %> </div>
</div> 

<div id="edit-button"><%= link_to 'Edit', edit_image_path(@image) %> </div>
<textarea id="svg-data"></textarea>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colour Therapy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body class="<%= @page_class %>">

<div id="nav-bar">
<nav>
	<ul>
<!-- 		<li><%= link_to image_tag("temp-logo.png", alt: "Temp Logo", height: "50px", width: "50px"), root_path%></li> -->
		<li class="logo"><%= link_to "CT", root_path%></li>

		<li><%= link_to "Categories", categories_path %> </li>

		<li><%= link_to "Gallery", root_path %></li>

		<li><% if current_user %>
				<%= link_to current_user.name, account_path %>
			<% else %>
				<%= link_to "Log In", login_path %>
			<% end %>
		</li>
	</ul>
</nav>
</div>

<div id="wrapper">
<%= yield %>
</div>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up to Colour Therapy</h1>

<div id="login">
<%= form_for(:user, url: '/users') do |f| %>

	<div id="name"><%= f.text_field :name, :placeholder => 'Name' %></div>
	<br>
	<div id="email"><%= f.email_field :email, :placeholder => 'Email'%></div>
	<br>
	<div id="password"><%= f.password_field :password, :placeholder => 'Password' %></div>
	<br>
	<div id="password_confirmation"><%= f.password_field :password_confirmation, :placeholder => 'Confirm Password' %></div>
	<br>
	<br>
	<div class="submit"><%= f.submit "Sign Up" %></div>
	Already have an account? <%= link_to "Log In", login_path %> now
</div>

<% end %>

app/views/users/show.html.erb
<h1>Account</h1>


<h3>Name: <span class="user-info"><%= @user.name %></span></h3>
<h3>Email: <span class="user-info"><%= @user.email %></span></h3>
<p><%= link_to "Log Out", logout_path %></p>

app/views/welcome/index.html.erb
	<div id="welcome"><%= link_to "Colour Therapy", categories_path %></div>